project_name: webhook

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      ldflags:
        - -w -s -X "github.com/soulteary/webhook/internal/version/version.Version={{ .Tag }}"
    id: macos
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: ["386", arm, amd64, arm64]
    goarm:
      - "7"
      - "6"

dockers:

  - image_templates:
      - "soulteary/webhook:linux-amd64-{{ .Tag }}"
      - "soulteary/webhook:linux-amd64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "soulteary/webhook:linux-arm64-{{ .Tag }}"
      - "soulteary/webhook:linux-arm64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm64
    goarm: ''
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "soulteary/webhook:linux-armv7-{{ .Tag }}"
      - "soulteary/webhook:linux-armv7"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "soulteary/webhook:linux-armv6-{{ .Tag }}"
      - "soulteary/webhook:linux-armv6"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "soulteary/webhook:linux-amd64-debug-{{ .Tag }}"
      - "soulteary/webhook:linux-amd64-debug"
    dockerfile: docker/Dockerfile.debug
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "soulteary/webhook:linux-arm64-debug-{{ .Tag }}"
      - "soulteary/webhook:linux-arm64-debug"
    dockerfile: docker/Dockerfile.debug
    use: buildx
    goos: linux
    goarch: arm64
    goarm: ''
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "soulteary/webhook:linux-armv7-debug-{{ .Tag }}"
      - "soulteary/webhook:linux-armv7-debug"
    dockerfile: docker/Dockerfile.debug
    use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

  - image_templates:
      - "soulteary/webhook:linux-armv6-debug-{{ .Tag }}"
      - "soulteary/webhook:linux-armv6-debug"
    dockerfile: docker/Dockerfile.debug
    use: buildx
    goos: linux
    goarch: arm
    goarm: "6"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/webhook"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.licenses=MIT"

docker_manifests:
  - name_template: "soulteary/webhook:{{ .Tag }}"
    image_templates:
      - "soulteary/webhook:linux-amd64-{{ .Tag }}"
      - "soulteary/webhook:linux-arm64-{{ .Tag }}"
      - "soulteary/webhook:linux-armv7-{{ .Tag }}"
      - "soulteary/webhook:linux-armv6-{{ .Tag }}"
    skip_push: "false"
  
  - name_template: "soulteary/webhook:debug-{{ .Tag }}"
    image_templates:
      - "soulteary/webhook:linux-amd64-debug-{{ .Tag }}"
      - "soulteary/webhook:linux-arm64-debug-{{ .Tag }}"
      - "soulteary/webhook:linux-armv7-debug-{{ .Tag }}"
      - "soulteary/webhook:linux-armv6-debug-{{ .Tag }}"
    skip_push: "false"

  - name_template: "soulteary/webhook:latest"
    image_templates:
      - "soulteary/webhook:linux-amd64-{{ .Tag }}"
      - "soulteary/webhook:linux-arm64-{{ .Tag }}"
      - "soulteary/webhook:linux-armv7-{{ .Tag }}"
      - "soulteary/webhook:linux-armv6-{{ .Tag }}"
    skip_push: "false"